### ISSUE TITLE
Build on Xcode 12.0.1 failing (swift compilation error)

### ISSUE THREAD

**Issue by gagandeep-s** [yasukotelin/ext_storage#7]
```
flutterSDK/.pub-cache/hosted/pub.dartlang.org/ext_storage-1.0.3/ios/Classes/ExtStoragePlugin.m:2:9: fatal error: 'ext_storage/ext_storage-Swift.h' file not found
#import <ext_storage/ext_storage-Swift.h>
        ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
1 error generated.

```

![image](https://user-images.githubusercontent.com/26773871/98670393-aa96f680-2378-11eb-9292-8574a8086a89.png)

![image](https://user-images.githubusercontent.com/26773871/98670360-9c48da80-2378-11eb-9d86-aae0f59b332b.png)

**Comment by gagandeep-s** [comment]
Please make it compilable on iOS swift.

**Comment by gagandeep-s** [comment]
`**This has been resolved now, below is the log of changes:**`

![image](https://user-images.githubusercontent.com/26773871/98678214-3b270400-2384-11eb-8de3-bb8ff3eaa614.png)

![image](https://user-images.githubusercontent.com/26773871/98678257-48dc8980-2384-11eb-9651-bc2f7a3c0d5a.png)
